openapi: 3.0.0
info:
  title: Merchant API
  version: '1.0'
  description: Create a hosted-checkout experience on Ablr web app
  contact:
    name: Developer Support
    email: developer@ablr.com
    url: 'https://www.ablr.com/contact-us'
servers:
  - url: 'https://api.uat.ablr.com/merchant/v1'
    description: (Staging)
  - description: (Production)
    url: 'https://api.ablr.com/merchant/v1'
paths:
  /checkouts/:
    parameters: []
    post:
      summary: Create a Checkout
      operationId: postcheckouts
      responses:
        '201':
          description: A new checkout object was created. Customer should be redirected to `checkout_url` to commence the checkout flow on Ablr.
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                  checkout_url:
                    type: string
                    minLength: 1
                    format: uri
                required:
                  - id
                  - checkout_url
              examples:
                Example (SG):
                  value:
                    id: Ya4r1PudO0B09Aaa4Y9vzhDM4xoRgz2SNZAGTes8AMS6tYGL41nT7JTsvdhD1bj1
                    checkout_url: 'https://app-uat.ablr.com/sg/checkouts/Ya4r1PudO0B09Aaa4Y9vzhDM4xoRgz2SNZAGTes8AMS6tYGL41nT7JTsvdhD1bj1/'
                Example (MY):
                  value:
                    id: LBfVq0QNQRmFr38tOWsNuiDO59dnWRmE0pqTGttk5dY1ha9po0av3SXkue2CPFFe
                    checkout_url: 'https://app-uat.ablr.com/my/checkouts/LBfVq0QNQRmFr38tOWsNuiDO59dnWRmE0pqTGttk5dY1ha9po0av3SXkue2CPFFe/'
      description: 'This request is made once the customer chooses to use Ablr as their payment method at checkout and will contain order and customer information. The Checkout API will then provide a response that includes a `checkout_url`, allowing you to point the customer to the Ablr checkout flow where they will complete their application or securely log in to their Ablr account to confirm the transaction.'
      security: []
      parameters:
        - schema:
            type: string
            example: Token gyR4jH4Nw3xJQr1p5U9fkzpZJEsXa8hM7e7y7Kgm
            default: Token gyR4jH4Nw3xJQr1p5U9fkzpZJEsXa8hM7e7y7Kgm
          in: header
          name: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                store:
                  type: string
                  description: Your store ID
                  example: SG-S-EF3478CEAW46
                email:
                  type: string
                  description: The customer's email address
                  format: email
                  example: john.doe@example.com
                first_name:
                  type: string
                  description: The customer's first name
                  example: John
                last_name:
                  type: string
                  description: The customer's last name
                  example: Doe
                amount:
                  type: integer
                  description: The total amount of the checkout in cents.
                  example: 123450
                currency:
                  type: string
                  enum:
                    - SGD
                    - MYR
                  description: The checkout currency
              required:
                - store
                - email
                - first_name
                - last_name
                - amount
                - currency
            examples:
              Example (SG):
                value:
                  store: SG-S-EF3478CEAW46
                  email: john.doe@example.com
                  first_name: John
                  last_name: Doe
                  amount: 123450
                  currency: SGD
              Example (MY):
                value:
                  store: MY-S-4PQNGRNGEF99
                  email: john.doe@example.com
                  first_name: John
                  last_name: Doe
                  amount: 678900
                  currency: MYR
  /charges/:
    post:
      summary: Capture a confirmed order
      responses:
        '201':
          description: Order was successfully captured. A Charge ID is returned for future reference.
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                required:
                  - id
              examples:
                Example (SG):
                  value:
                    id: CWd9cPNMNGDCVDEEjR50hLiyRbiZNFvhusX4p6DJXPMfQpFnJTMbueFvJLmwBwCu
                Example (MY):
                  value:
                    id: o1aEgD2y4h8cGqb7ZjNbJrRMvjZzNJXUE4LbGSqB23eacR28MgIjhiYdcxINueCT
      operationId: post-charges
      description: |-
        **If you opt out Ablr's automatic capture**, you must call this `/charges/` endpoint to manually capture the fund for the disbursement to the merchant the next business day. You only get paid when the order has been captured.

        When the customer confirms to pay for an order on Ablr web app, they will be redirected to your `confirm_url` immediately with `ablr_order_code` and `state` query parameters (`state` param will have value of `confirm`).
      parameters:
        - schema:
            type: string
            default: Token gyR4jH4Nw3xJQr1p5U9fkzpZJEsXa8hM7e7y7Kgm
            example: Token gyR4jH4Nw3xJQr1p5U9fkzpZJEsXa8hM7e7y7Kgm
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                order:
                  type: string
                  minLength: 1
              required:
                - order
            examples:
              Example (SG):
                value:
                  order: SG-O-BC3VWRAHGV
              Example (MY):
                value:
                  order: MY-O-RQJ7JDK7WD
        description: ''
components:
  schemas: {}
  securitySchemes: {}
security:
  - API Key - 1: []
